### ISSUE TITLE
Raspberry 1 arm32/v6 error

### ISSUE THREAD

**Issue by tanus10** [dockhippie/mariadb#30]
```
Creating mariadb ... done
Attaching to mariadb
mariadb          | > writing mariadb config
mariadb          | ./setup: line 7:    18 Illegal instruction     (core dumped) /usr/bin/gomplate -V -o /etc/mysql/my.cnf -f /etc/templates/my.cnf.tmpl
mariadb exited with code 0
```
Maybe something is not compatible with arm32/v6?
Many arm docker images are only arm32/v7 compatible. Unable to run on Raspberry Pi 1/zero

```
    mariadb:
      container_name: mariadb
      image: webhippie/mariadb:latest-arm32v6 
      environment:
        - CRON_ENABLED=false
        - TZ=xxx/xxxx
        - MARIADB_DEFAULT_CHARACTER_SET=utf8
        - MARIADB_ROOT_PASSWORD=xxxxx
      volumes:
        - /tmp:/etc/mysql/conf.d
        - /opt/mariadb3:/var/lib/mysql
      ports:
        - "3306:3306"
```
