### ISSUE TITLE
`command` not working

### ISSUE THREAD

**Issue by Myzel394** [dockhippie/mariadb#47]
I'm trying to setup a NextCloud server and for this a custom `command` needs to be specified (see https://techoverflow.net/2021/08/17/how-to-fix-nextcloud-4047-innodb-refuses-to-write-tables-with-row_formatcompressed-or-key_block_size/).

Here is a snippet of my `docker-compose.yml`:

```yaml
nextcloud_db:
    image: webhippie/mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    container_name: nextcloud_db
    restart: unless-stopped
    volumes:
        - ./db:/var/lib/mysql
    environment:
        - MARIADB_ROOT_PASSWORD=noice
        - MARIADB_PASSWORD=noice
        - MARIADB_DATABASE=nextcloud
        - MARIADB_USERNAME=nextcloud
```
